language: node_js
sudo: required
dist: trusty
node_js: stable
#addons:
#  firefox: latest
#  sauce_connect:
#    username: "Your Sauce Labs username"
#    access_key: "Your Sauce Labs access key"
#  apt:
#    sources:
#    - google-chrome
#    packages:
#    - google-chrome-stable
cache:
  directories:
  - node_modules
notifications:
  slack:
    on_success: change
    on_failure: always
    secure: pBrIUbFVwV2R7VKyZu6ze0oSgf4KBGVNR4tVoTT7G7OiW/UiS6IUNAufC+1yviq34O3AomVn1bOmOt411vttzbQfFtG4f+toLNYdul2HD0cCQQrvreSOVvCTvU7ki8MoxdI3IeF47pUta1q5z22g4s953hAlG6Mr3TsZEqtg4YTO/KC+nN/MUQ9CsLqx+47PkbyF2xOcTs1tK78Gwf+v8ZoGBF9yYxj5WeC/fsxaIidx9wbvcLmHNWzExOuYflXl89M3mTJntWqtMzGFcgOcvDgXb23UMo4Efr1r6MKio1BOOUGmKa/WeuhW3W9JvFFszNyGR35F38b/fPkHBAh0zMIQZIvS9xvDlGUdlT+LyMN0GLxWBhtdxP8JNlm9PocuS7uULfTs7lb4nzocVeU72tJyqxNi4T3urhXpbzK4yKvTTY4G5qqbfLJeJO7pVrudU6w0F1VXwUWf8OJC1zlmEo9mmBRE7/vYT227lKDtnvkyHXUGARz2EB6etjrcvQMiX/gbTwQxVKClarZwZGc6RY1rKkKydzbtcBO/5Q0VGt1DM/HMrweYrwlOTUBtJeffdkyfoqwJbA9sz9rN1W5n9TJoSvje+RPl3B/O+gf5mv7qFmk4bakvRdVUus7wiPjGu3PWbNNPfUw47j5ehpEbwDpJiXC5E5MOHTpFqQir4Wo=
